version: '3.5'

services:
    web-api-development:
        build:
            context: .
            dockerfile: ./Dockerfile.development
        image: bromuro-api-development
        environment:
            PORT: 3000
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_SERVER_ADDRESS: mysql
            MYSQL_SERVER_PORT: '${MYSQL_SERVER_PORT}'
        restart: always
        depends_on:
            - mysql
        volumes:
            - ./src:/var/www/app/src
        ports:
            - 3000:3000

    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'bromuro'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
        volumes:
            - ./mysql-volume:/var/lib/mysql
        ports:
            - 3306:3306

    adminer:
        image: adminer
        environment:
            ADMINER_DEFAULT_SERVER: mysql
        depends_on:
            - mysql
        ports:
            - 8080:8080

volumes:
    mysql-volume:
        name: mysql-volume
