version: '3.5'

services:
    web-api:
        image: l3bowski/bromuro-api:latest
        environment:
            PORT: 80
            MONGODB_ROOT_USER: '${MONGODB_ROOT_USER}'
            MONGODB_ROOT_PASSWORD: '${MONGODB_ROOT_PASSWORD}'
            MONGODB_SERVER_ADDRESS: 'mongo'
            MONGODB_SERVER_PORT: '${MONGODB_SERVER_PORT}'
        depends_on:
            - 'mongo'
        ports:
            - 80:80

    mongo:
        image: 'mongo'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGODB_ROOT_USER}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_ROOT_PASSWORD}'
        volumes:
            - ./mongodb-volume:/data/db
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: '${MONGODB_ROOT_USER}'
            ME_CONFIG_MONGODB_ADMINPASSWORD: '${MONGODB_ROOT_PASSWORD}'
        depends_on:
            - 'mongo'
        ports:
            - 8081:8081

volumes:
    mongodb-volume:
        name: mongo-volume
