version: '3.5'

services:
    mongo:
        image: 'mongo'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGODB_ROOT_USER}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_ROOT_PASSWORD}'
        volumes:
            - ./mongodb-volume:/data/db
        ports:
            - '27017:27017'

    mongo-express:
        image: mongo-express
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: '${MONGODB_ROOT_USER}'
            ME_CONFIG_MONGODB_ADMINPASSWORD: '${MONGODB_ROOT_PASSWORD}'
        depends_on:
            - 'mongo'
        ports:
            - 8081:8081

volumes:
    mongodb-volume:
        name: mongo-volume
