version: '3.5'

services:
    web-api:
        build: ./
        # TODO Serve directly from the source file
        environment:
            PORT: 80
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_SERVER_ADDRESS: mysql
            MYSQL_SERVER_PORT: '${MYSQL_SERVER_PORT}'
        depends_on:
            - mysql
        ports:
            - 80:80

    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'bromuro'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
        volumes:
            - ./mysql-volume:/var/lib/mysql
        ports:
            - 3306:3306

    adminer:
        image: adminer
        environment:
            ADMINER_DEFAULT_SERVER: mysql
        depends_on:
            - mysql
        ports:
            - 8080:8080

volumes:
    mysql-volume:
        name: mysql-volume
